### ISSUE TITLE
Getting unhandled asynchronous exception: TypeError: Cannot read property 'passes' of undefined

### ISSUE THREAD

**Issue by Sumit-Soman** [mocha-parallel/mocha-parallel-tests#221]
Error:
Unhandled asynchronous exception: TypeError: Cannot read property 'passes' of undefined
    at Spec.Base.epilogue (C:\Users\S730737\Documents\EK.com\Projects\carbon-ui-automation\node_modules\mocha\lib\reporters\base.js:318:26)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at RunnerMain.emit (events.js:208:7)
    at RunnerMain.emitFinishEvents (C:\Users\S730737\Documents\EK.com\Projects\carbon-ui-automation\node_modules\mocha-parallel-tests\dist\main\runner.js:31:14)
    at TaskManager.taskManager.on.on (C:\Users\S730737\Documents\EK.com\Projects\carbon-ui-automation\node_modules\mocha-parallel-tests\dist\main\mocha.js:92:20)
    at emitNone (events.js:106:13)
    at TaskManager.emit (events.js:208:7)
    at TaskManager.emitEndIfAllFinished (C:\Users\S730737\Documents\EK.com\Projects\carbon-ui-automation\node_modules\mocha-parallel-tests\dist\main\task-manager.js:49:18)
    at TaskManager.onTaskProcessingFinished (C:\Users\S730737\Documents\EK.com\Projects\carbon-ui-automation\node_modules\mocha-parallel-tests\dist\main\task-manager.js:21:18)

Same code working fine with serial order
mocha-parallel-tests --opts ./mocha.opts ./src/tests/**.spec.js --slow 100
Kindly advice

**Comment by Sumit-Soman** [comment]
Have tired downgraded version as well.

**Comment by Danielv123** [comment]
Same problem here,

`
    "mocha": "^6.1.2",
    "mocha-parallel-tests": "^2.0.6-alpha.3"
`

**Comment by Danielv123** [comment]
Downgraded to mocha 5.2.0 and it now works.

`npm i --save-dev mocha@5`

Readme doesn't mention supporting mocha 6, so it shouldn't be that surprising.

**Comment by 1999** [comment]
Thanks @Danielv123 @Sumit-Soman for reporting this. Any ideas what's new in mocha@6 which is a breaking change with mocha@5?

**Comment by Danielv123** [comment]
I do not follow development of either tool closely enough to hazard a guess. Since this is an issue relating to using an unsupported version of mocha, I suggest we close this issue and continue discussion related to problems with mocha 6 in #217

**Comment by 1999** [comment]
Nice catch, looks like it has already been reported. I'll close this issue then.
