### ISSUE TITLE
"--reporter-options option can be specified only once" error using Mocha 6

### ISSUE THREAD

**Issue by renataogarcia** [mocha-parallel/mocha-parallel-tests#232]
```
"mocha": "^6.1.4"
"mocha-parallel-tests": "^2.1.0"
```
When using `--reporter-options' and Mocha 6 the following exception is raised:
```
Uncaught exception: AssertionError [ERR_ASSERTION]: --reporter-options option can be specified only once
    at Object.applyReporterOptions [as default] (.../node_modules/mocha-parallel-tests/src/bin/options/reporter-options.ts:9:5)
    at Object.<anonymous> (.../node_modules/mocha-parallel-tests/src/bin/cli.ts:171:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
It works fine when using `mocha@^5.2.0`

When using version 6 the `reporterOptions` is an `array` instead of a `string` causing the exception:
https://github.com/mocha-parallel/mocha-parallel-tests/blob/b310aec9ecbc49dfe663c51fb1bcfcf6f3ffd101/src/bin/options/reporter-options.ts#L5

Maybe it will require a similar approach to what's being done for the `--no-timeout(s)` option?
https://github.com/mocha-parallel/mocha-parallel-tests/blob/b310aec9ecbc49dfe663c51fb1bcfcf6f3ffd101/src/bin/cli.ts#L35-L50

**Comment by 1999** [comment]
Thanks @renataogarcia looks like I overlooked this and we didn't have a test for `--reporter-options` CLI flag. I will fix it.

**Comment by renataogarcia** [comment]
@1999 Fantastic - Thanks!

**Comment by 1999** [comment]
@renataogarcia `mocha-parallel-tests@2.1.1` contains the fix. Please, check it when you have time and re-open the issue if it doesn't work.
